# Generated by Django 4.1.4 on 2022-12-12 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('foto', models.ImageField(default=None, upload_to='images/')),
                ('descripcion', models.TextField(max_length=400)),
                ('tags', models.CharField(max_length=100)),
                ('url_github', models.URLField()),
            ],
        ),
    ]
