# Generated by Django 3.2.8 on 2023-02-10 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_alter_project_foto_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='foto_img',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
